### ISSUE TITLE
The parentPath of a "List files" request is invalid

### ISSUE THREAD

**Issue by valhaal** [AnnotationSro/ng6-file-man#11]
Hello.
I downloaded the demo app and am trying to use it. I made a simple .net core API to provide data for it.
Everything works fine on surface, but when I create a folder deeper, than in root folder - the paretnPath parameter is wrong when I click on it.
E.g.
Initiate app (GET root folder). The app sends a http request to the URL "https://localhost:44356/api/files/list?parentPath=" and it works fine.
Click on a folder "Test1" in root dir. The app sends a http request to the URL "https://localhost:44356/api/files/list?parentPath=Test1" and it works fine.
Click on a folder "Test2" in "Test1" dir. The app sends a http request to the URL "https://localhost:44356/api/files/list?parentPath=Test2", but the "parentPath" should be "=Test1/Test2". 
The return JSONs, returned from an API when browsing to a folders are:
[{"size":"0","url":"/Test1","id":"Test1","dir":true,"path":"/Test1","name":"Test1"}]
[{"size":"0","url":"/Test1/Test2","id":"Test2","dir":true,"path":"/Test1/Test2","name":"Test2"}]

Am I doing something wrong, or it's a bug?

**Comment by Chiff** [comment]
This seems to be working on current version.

Create new issue if it persists,
