### ISSUE TITLE
 impossible to understand the parentpath system

### ISSUE THREAD

**Issue by jonatmoy** [AnnotationSro/ng6-file-man#20]
Hello, i've download the api, but i can't understand the system of parentpath. I try to use postman to call your api, 
but it does not work. 
There is a "files" folder at the root is this where the root of the API starts? I put a filled folder in the file folder called "back".
![image](https://user-images.githubusercontent.com/34139071/85571773-b6398900-b634-11ea-9a7f-6ce98b9a6b82.png)
![image](https://user-images.githubusercontent.com/34139071/85571987-e719be00-b634-11ea-81fc-a62e00512931.png)
I've been trying to make it work for 3 hours that I don't understand, can you help me?

**Comment by Chiff** [comment]
**ng6-file-man-express** has defined endpoints like `api/list` etc. while **ng6-file-man** demo expects `api/file/list`

more info by @jonatmoy on https://stackoverflow.com/a/62569441/5011810
