### ISSUE TITLE
Can we get some images of the component in the readme?

### ISSUE THREAD

**Issue by PixelPerfectJenna** [AnnotationSro/ng6-file-man#27]
Can we get some images of the component in the readme? Just think it would help new users (like me) decided if they would like to invest time into using this component.

**Comment by Chiff** [comment]
1e0806533aab252fda4926e542ce27fc9df9a8f1

images are added, please bear in mind that you can easily edit visual of some parts of components with:
* scss variables
* override style classes 
* use own angular #templates to modify strucure
