### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by ChiKaLiO** [AnnotationSro/ng6-file-man#30]
I followed the steps on readme:

i18n

- Copy i18n file from ~node_modules/ng6-file-man/assets
- Put it in ~src/assets/i18n/[language].json (e.g. ~src/assets/i18n/fr.json)
- Fill empty strings with your translations (e.g. "Download": "Télécharger")
- Set language property <fm-file-manager [language]="'fr'" ... ></fm-file-manager>

Voilà...

But nothung happened, even english not working..

**Comment by Chiff** [comment]
We have moved file manager translate strings into object `filemanager`. But we have forgotten to update assets. Thanks for pointing that out. Here is the new `sk.json`.

We will update the package later

```
"filemanager": {
    "cancel": "Zrušiť",
    "close": "Zavrieť",
    "confirm": "Potvrdiť",
    "create_new_folder": "Vytvoriť nový priečinok",
    "delete": "Vymazať",
    "download": "Stiahnuť",
    "file_name": "Názov súboru",
    "folder_name": "Názov priečinku",
    "new_name": "Nový názov",
    "no": "Nie",
    "no_data": "Žiadne dáta",
    "no_results": "Nenašli sa žiadne výsledky pre",
    "Ok": "Ok",
    "old_name": "Starý názov",
    "open_file_manager": "Otvoriť správcu súborov",
    "processing_dropped_files": "Spracovávam vložené súbory",
    "processing_request": "Spracovávam požiadavok",
    "rename": "Premenovať",
    "rename_file": "Premenuj súbor",
    "retry": "Skúsiť znova",
    "search": "Hľadať",
    "search_results_for": "Výsledky hľadania pre",
    "size": "Veľkosť",
    "something_went_wrong_with_your_request": "Nastal problem pri spracovávaní požiadavku.",
    "loading_troubles": "Problémy s načítavaním? Kliknite na zrušenie načítavania",
    "type_new_folder_name": "Napíšte názov nového priečinku",
    "upload": "Nahrať",
    "upload_file": "Nahrať súbor",
    "yes": "Áno",
    "yes_delete_this": "Vymazať  ",
    "file_delete_confirm": "Naozaj chcete vymazať tento",
    "file": "súbor",
    "folder": "priečinok",
    "confirm_selection": "Potvrdiť",
    "cancel_selection": "Zrušiť",
    "drop_zone_label": "Sem môžete potiahnuť súbory"
  },
```

**Comment by ChiKaLiO** [comment]
Well thanks, keep it up

Here is english translation:

`{
  "filemanager": {
      "cancel": "Cancel",
      "close": "Close",
      "confirm": "Confirm",
      "create_new_folder": "Create new folder",
      "delete": "Delete",
      "download": "Download",
      "file_name": "File Name",
      "folder_name": "Folder Name",
      "new_name": "New Name",
      "no": "No",
      "no_data": "No Data",
      "no_results": "No Results",
      "Ok": "Ok",
      "old_name": "Old Name",
      "open_file_manager": "Open File Manager",
      "processing_dropped_files": "Processing Dropped Files",
      "processing_request": "Processing Request",
      "rename": "Rename",
      "rename_file": "Rename File",
      "retry": "Retry",
      "search": "Search",
      "search_results_for": "Search Results For",
      "size": "Size",
      "something_went_wrong_with_your_request": "Something Went Wrong With Your Request.",
      "loading_troubles": "Loading problems",
      "type_new_folder_name": "Type New Folder Name",
      "upload": "Upload",
      "upload_file": "Upload File",
      "yes": "Yes",
      "yes_delete_this": "Yes delete  ",
      "file_delete_confirm": "Are you sure",
      "file": "File",
      "folder": "Folder",
      "confirm_selection": "Confirm Selection",
      "cancel_selection": "Cancel Selection",
      "drop_zone_label": "Drop Files Here"
    }
  }`
