### ISSUE TITLE
Setting up default fine-upload is non-trivial

### ISSUE THREAD

**Issue by briangmilnes** [AnnotationSro/ng6-file-man#5]
There are loads of documentation which are not clear on how to setup the backend to even see this project.
Fine-upload setup in the php-traditional is just not clear unless somehow you have experience in PHP
webserver setup. If you want people to be able to try your application without hours of pain, you should
build a fully running git project with the backend API ready to run.

**Comment by kaiiorg** [comment]
Its been a few months since you opened this issue; did you ever figure out how to implement the API, including the file upload?

**Comment by Chiff** [comment]
Feel free to try out new Express API https://github.com/Chiff/ng6-file-man-express
