### ISSUE TITLE
using the filemanager api in a real angular project

### ISSUE THREAD

**Issue by sancelot** [AnnotationSro/ng6-file-man#6]
** usage **
I made an angular project in order to use it.
unfortunately, the filemanager service at localhost:8080 does not launch.

**To Reproduce**
my project is shared in github
https://github.com/sancelot/ng6-file-man-demo

**Expected behavior**
being able to use the filemanager api

**Comment by Chiff** [comment]
There is no FileManager API in this project right now. You have to create API based on documentation.

**Comment by Chiff** [comment]
Feel free to try out new Express API https://github.com/Chiff/ng6-file-man-express
