### ISSUE TITLE
Tree view - Folders

### ISSUE THREAD

**Issue by dj-milenkovic** [AnnotationSro/ng6-file-man#7]
How I can create folders in a folder? Do you have documentation? I'm using 1.0.6. version

**Comment by Chiff** [comment]
* On frontend part click on `+` button (always last in node list)

![new_file_fe](https://user-images.githubusercontent.com/10731497/62872697-51c45280-bd1e-11e9-8cb2-e7c0838ccf07.png)

* On `filemanager.confirm` we will send POST to API which will look like this:
`http://localhost:8080/api/directory?dirName=test&parentPath=/docosaurus`

* Then on backend you will need to create folder on fs

**Comment by dj-milenkovic** [comment]
Yeah, I know that but I have a problem adding folder and files in created folder. I can add folders and files in root but not in sub folder... I got error: nodes - undefined when I double click my folder. How should I read my files and folders?

**Comment by dj-milenkovic** [comment]
![image](https://user-images.githubusercontent.com/18371654/62925654-19bb1f00-bdb3-11e9-830f-a8b5a10d51ff.png)

**Comment by Chiff** [comment]
I reproduced your steps with https://github.com/Chiff/ng6-file-man-express backend and no error occured. 

With your description of problem and output I cannot identify the source of problem. Please attach error log (stacktrace), steps to reproduce the problem with your code and any other useful data.

**Comment by dj-milenkovic** [comment]
Maybe my nodes aren't correctly created. This is my columns in the table:
- [id]
- [content_type]
- [size]
- [url]
- [dir]
- [path]
- [name]
- [folder_name]
- [client_id]
- [document_type_id]
- [document_segment_id]
- [description]

So how do you know how to open a folder? Is path or url vital? Path and Url are the same in my way and both have the full path to the file or folder

**Comment by Chiff** [comment]
Check doc https://github.com/AnnotationSro/ng6-file-man#list-files--folders. It is important to return all required information based on `NodeInterface`. 

* `NodeInterface.url` is for downloads 
* `NodeInterface.path` is required for file manager to navigate
* `NodeInterface.id` is required for identifying elements

**Comment by dj-milenkovic** [comment]
Yeah and that's all right, but does path need to be full like C:/Documents/Project/Doc... or it needs to be only /Doc/...

**Comment by Chiff** [comment]
Needs to be relative on root folder. Please check out https://github.com/Chiff/ng6-file-man-express for detailed information on how API should work.

**Comment by bhagyashreeShinde** [comment]
how to add children to the folder? on click of folder we are getting the side view. easy and simple solution
