### ISSUE TITLE
Allow to disable file download on double click

### ISSUE THREAD

**Issue by novice3030** [AnnotationSro/ng6-file-man#8]
Hi, I love this component but I want to use it just as a file selector I have no need for download on double click how can I disable it?
If you want I can submit a pull request that does just that.

**Comment by Chiff** [comment]
@IgorKvasn if I'm right you were working on this. Did you finish it?

**Comment by IgorKvasn** [comment]
@Chiff hmm does not ring a bell, but it sure sounds good! We should definitely implement it 👍

**Comment by novice3030** [comment]
Thanks guys

**Comment by Chiff** [comment]
I was referencing to code below

```
<div class="file-manager-backdrop" *ngIf="fmOpen">
    <div class="fmModalInside">
      <div *ngIf="fmOpen; then showContent"></div>
      <div class="buttons-panel">
        <button class="button big" (click)="confirmSelection()" [disabled]="!selectedNode">{{'filemanager.confirm_selection' | translate}}</button>
        <button class="button big" (click)="cancelSelection()">{{'filemanager.cancel_selection' | translate}}</button>
      </div>
    </div>
  </div>
```

When you use FM as popup and click once on some file/folder there is a button that emits selected node and closes FM.

I would set this behavior to be optional in both normal and popup mode.

---

Download button can be currently disabled only for folders. (`\file-manager\interfaces\config.interface.ts:15`). 

Maybe we should change it to `downloadMode: DownloadModeEnum` 

```
export enum DownloadModeEnum {
    DISABLED, FILES_ONLY, ALL
}
```

**Comment by Chiff** [comment]
added in version 2.2.0
