### ISSUE TITLE
update ngrx store to latest version and fix breaking changes

### ISSUE THREAD

**Issue by novice3030** [AnnotationSro/ng6-file-man#9]
Users of this project who are also using ngrx store with newer version in their project currently can't compile to AOT cause of breaking changes in ngrx store.
The project needs to be updated to latest version of ngrx store and fix the breaking changes

**Comment by Chiff** [comment]
#10

**Comment by Chiff** [comment]
Fixed with pre-release 2.1.3
Next release will remove NGRX/store and some other packages
